name: 'LLM Code Review'
description: 'A container GitHub Action to review a pull request by HuggingFace LLM Model.'
author: 'Louis Le (luiyen)'
inputs:
  githubToken:
    description: 'Github token to access the repo'
    required: true
  apiKey:
    description: 'Huggingface access token from [https://huggingface.co/settings/tokens](https://huggingface.co/settings/tokens)'
    required: False
  repo:
    description: "The GitHub repository to use for the action"
    required: true
    default: "${{ github.repository }}"
  pr_number:
    description: "The GitHub pull request number to use for the action"
    required: true
    default: "${{ github.event.pull_request.number }}"
  model:
    description: "LLM model"
    required: Flase
    default: ""
  
runs:
  using: docker
  image: Dockerfile
  env:
    API_KEY: ${{ inputs.apiKey }}
    GITHUB_TOKEN: ${{ inputs.githubToken }}
    GITHUB_REPOSITORY: ${{ inputs.githubRepository }}
    GITHUB_PULL_REQUEST_NUMBER: ${{ inputs.githubPullRequestNumber }}
    GIT_COMMIT_HASH: ${{ inputs.gitCommitHash }}
  args:
    - "--model=${{inputs.model}}"
    - "--repo=${{ inputs.githubRepository }}"
    - "--pr_number=${{inputs.pr_number}}"
