name: 'LLM Code Review'
description: 'A container GitHub Action to review a pull request by HuggingFace LLM Model.'
author: 'Louis Le (luiyen)'
inputs:
  githubToken:
    description: 'Github token to access the repo'
    required: true
  apiKey:
    description: 'Huggingface access token from [https://huggingface.co/settings/tokens](https://huggingface.co/settings/tokens)'
    required: False
  repo:
    description: "The GitHub repository to use for the action"
    required: true
    default: "KondalaYaswanth/admin_portal"
  pr_number:
    description: "The GitHub pull request number to use for the action"
    required: true
    default: "${{ github.event.pull_request.number }}"
  model:
    description: "LLM model"
    required: true
    default: ""
  pr_authoremail:
    description: "user email"
    required: true
    default: ""
  SENDER_EMAIL:
    description: "sender email"
    required: true
    default: "null"
  SENDER_PASSWORD:
    description: "app password is required dont use personal email password"
    required: true
    default: "null"
  
runs:
  using: docker
  image: Dockerfile
  env:
    API_KEY: ${{ inputs.apiKey }}
    GITHUB_TOKEN: ${{ inputs.githubToken }}
    SENDER_EMAIL: ${{inputs.SENDER_EMAIL}}
    SENDER_PASSWORD: ${{inputs.SENDER_PASSWORD}}
    
  args:
    - "--model=${{inputs.model}}"
    - "--repo=${{ inputs.repo }}"
    - "--pr_number=${{inputs.pr_number}}"
    - "--pr_authoremail=${{inputs.pr_authoremail}}"
