name: "Test Code Review"

on:
  pull_request:
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: "Get diff of the pull request"
        id: get_diff
        shell: bash
        env:
          PULL_REQUEST_HEAD_REF: "${{ github.event.pull_request.head.ref }}"
        run: |-
          git fetch origin "${{ env.PULL_REQUEST_HEAD_REF }}:${{ env.PULL_REQUEST_HEAD_REF }}"
          git checkout "${{ env.PULL_REQUEST_HEAD_REF }}"
          git diff "origin/${{ env.PULL_REQUEST_HEAD_REF }}" > "diff.txt"
          # shellcheck disable=SC2086
          echo "diff=$(cat "diff.txt")" >> $GITHUB_ENV
      - uses: ./
        name: "Code Review"
        id: review
        with:
          apiKey: ${{ secrets.API_KEY }}||""
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          repo: "KondalaYaswanth/admin_portal"
          pr_number: ${{ github.event.pull_request.number }}
          model: "ollama:llama3"
          pr_authoremail: ${{ github.event.pull_request.user.email || '' }}
          SENDER_EMAIL: ${{secrets.SENDER_EMAIL||"null"}}
          SENDER_PASSWORD: ${{secrets.SENDER_PASSWORD||"null"}}

